"""creating songs and playlist tables using flask migrate

Revision ID: 6611dcd10789
Revises: 
Create Date: 2026-08-04 22:55:47.628581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6611dcd10789'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('song',
    sa.Column('song_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('artist', sa.String(length=300), nullable=False),
    sa.Column('album', sa.String(length=300), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('play_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('song_id'),
    sa.UniqueConstraint('file_path')
    )
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_song_album'), ['album'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_artist'), ['artist'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_is_favorite'), ['is_favorite'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_title'), ['title'], unique=False)

    op.create_table('playlist_songs',
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['song_id'], ['song.song_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('playlist_id', 'song_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_songs')
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_song_title'))
        batch_op.drop_index(batch_op.f('ix_song_is_favorite'))
        batch_op.drop_index(batch_op.f('ix_song_artist'))
        batch_op.drop_index(batch_op.f('ix_song_album'))

    op.drop_table('song')
    op.drop_table('playlist')
    # ### end Alembic commands ###
